<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class s012_Jadwal extends Seeder
{
    public function run()
    {
        //
        $jadwal = [
            // senin 
            // tkj
			[
				'id_jadwal'       => '1',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '1',
                'id_kelas'        => '1',
                'id_guru'         => '1',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '2',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '2',
                'id_kelas'        => '1',
                'id_guru'         => '2',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '3',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '3',
                'id_kelas'        => '1',
                'id_guru'         => '3',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '4',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '4',
                'id_kelas'        => '1',
                'id_guru'         => '4',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // rpl
			[
				'id_jadwal'       => '5',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '16',
                'id_kelas'        => '2',
                'id_guru'         => '4',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '6',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '17',
                'id_kelas'        => '2',
                'id_guru'         => '3',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '7',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '18',
                'id_kelas'        => '2',
                'id_guru'         => '2',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '8',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '1',
                'id_kurikulum'    => '19',
                'id_kelas'        => '2',
                'id_guru'         => '1',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // selasa
            // tkj
			[
				'id_jadwal'       => '9',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '5',
                'id_kelas'        => '1',
                'id_guru'         => '1',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '10',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '6',
                'id_kelas'        => '1',
                'id_guru'         => '2',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '11',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '7',
                'id_kelas'        => '1',
                'id_guru'         => '3',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '12',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '8',
                'id_kelas'        => '1',
                'id_guru'         => '4',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // rpl
			[
				'id_jadwal'       => '13',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '20',
                'id_kelas'        => '2',
                'id_guru'         => '4',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '14',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '21',
                'id_kelas'        => '2',
                'id_guru'         => '3',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '15',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '22',
                'id_kelas'        => '2',
                'id_guru'         => '2',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '16',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '2',
                'id_kurikulum'    => '23',
                'id_kelas'        => '2',
                'id_guru'         => '1',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // rabu
            // tkj
			[
				'id_jadwal'       => '17',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '9',
                'id_kelas'        => '1',
                'id_guru'         => '1',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '18',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '10',
                'id_kelas'        => '1',
                'id_guru'         => '2',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '19',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '11',
                'id_kelas'        => '1',
                'id_guru'         => '3',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '20',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '12',
                'id_kelas'        => '1',
                'id_guru'         => '4',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // rpl
			[
				'id_jadwal'       => '21',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '24',
                'id_kelas'        => '2',
                'id_guru'         => '4',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '22',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '25',
                'id_kelas'        => '2',
                'id_guru'         => '3',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '23',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '26',
                'id_kelas'        => '2',
                'id_guru'         => '2',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '24',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '3',
                'id_kurikulum'    => '27',
                'id_kelas'        => '2',
                'id_guru'         => '1',
                'jam_mulai'       => '12:30',
                'jam_akhir'       => '14:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // kamis
            // tkj
			[
				'id_jadwal'       => '25',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '13',
                'id_kelas'        => '1',
                'id_guru'         => '1',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '26',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '14',
                'id_kelas'        => '1',
                'id_guru'         => '2',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '27',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '15',
                'id_kelas'        => '1',
                'id_guru'         => '3',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // rpl
			[
				'id_jadwal'       => '29',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '28',
                'id_kelas'        => '2',
                'id_guru'         => '4',
                'jam_mulai'       => '07:00',
                'jam_akhir'       => '08:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '30',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '29',
                'id_kelas'        => '2',
                'id_guru'         => '3',
                'jam_mulai'       => '08:30',
                'jam_akhir'       => '10:00',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
			[
				'id_jadwal'       => '31',
                'id_tahun_ajaran' => '2',
                'id_hari'         => '4',
                'id_kurikulum'    => '30',
                'id_kelas'        => '2',
                'id_guru'         => '2',
                'jam_mulai'       => '10:00',
                'jam_akhir'       => '11:30',
                'tgl_uts'         => '',
                'jam_mulai_uts'   => '',
                'jam_akhir_uts'   => '',
                'id_soal_uts'     => '',
                'tgl_uas'         => '',
                'jam_mulai_uas'   => '',
                'jam_akhir_uas'   => '',
                'id_soal_uas'     => '',
            ],
            // jumat sabtu gak ada jadwal ceritanya haha
		];
        foreach($jadwal as $data){
			// insert semua data ke tabel
			$this->db->table('jadwal')->insert($data);
		}
    }
}
